# .github/actions/run-integrationstudio-load/action.yml

name: "Run IntegrationStudio Load Test"
description: "Executes JMeter test for IntegrationStudio and pushes metrics"

inputs:
  env_name:
    required: true
    type: string
  is-automation:
    required: true
    type: boolean
  is-scheduled:
    required: true
    type: boolean
  company-name:
    required: true
    type: string
  runner-label:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Run IntegrationStudio JMeter Load
      shell: pwsh
      run: |
        Write-Host "Running IntegrationStudio_ECKSSO_LOAD test mars action"
        $jmeterFile = "HR\\Main\\BJE\\IntegrationStudio_ECKSSO_LOAD.jmx"
        $envName = "${{ inputs.env_name }}"
        $gitRoot = "${{ github.workspace }}"
        $isAutomation = "${{ inputs.is-automation }}"
        $isScheduled = "${{ inputs.is-scheduled }}"
        $jmeterProperties = "-JINP_CompanyName=${{ inputs.company-name }}"

        .\PowerShell\Jmeter\JmeterRunTestInfluxdb.ps1 `
          -JmeterFile $jmeterFile `
          -Envname $envName `
          -GitRootFolder $gitRoot `
          -IsAutomation $isAutomation `
          -AdditionalInputVariables $jmeterProperties `
          -IsScheduled $isScheduled `
          -save $true `
          -run $true
