# .github/actions/deploy-jmeter/action.yml

name: "Deploy JMeter Scripts"
description: "Deploys JMeter scripts to the test node"

inputs:
  jmeter-test-node:
    required: true
    type: string
  jmeter-test-path:
    required: true
    type: string
  powershell-path:
    required: true
    type: string
  login-user:
    required: true
    type: string
  login-password:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy JMeter scripts via PowerShell
      shell: pwsh
      run: |
        Write-Host "Deploying JMeter scripts to ${{ inputs.jmeter-test-node }}"
        Write-Host "Jmeter test path to ${{ inputs.jmeter-test-path }}"
        Write-Host "Powershell path  ${{ inputs.powershell-path }}"
        Write-Host "Login user ${{ inputs.login-user }}"
        Write-Host "Secret login password ${{ inputs.login-password }}"

        $arguments = @(
          '-Servers', "${{ inputs.jmeter-test-node }}",
          '-JmeterTestPath', "${{ inputs.jmeter-test-path }}",
          '-PowershellPath', "${{ inputs.powershell-path }}",
          '-User', "${{ inputs.login-user }}",
          '-Password', "${{ inputs.login-password }}"
        )

        & .\PowerShell\Jmeter\DeployJmeterScripts.ps1 @arguments

        Write-Host "JMeter scripts deployed Jupiter actions successfully......."
