name: Integration Studio Workflow

on:
  workflow_dispatch:
    inputs:
      runner-label:
        required: true
        type: string
        default: "windows"
      jmeter-test-node:
        required: true
        type: string
        default: "azg5perftag001.CUSTADDS.com"
      jmeter-test-path:
        required: true
        type: string
        default: "JMeterTests\\src\\jmeter"
      powershell-path:
        required: true
        type: string
        default: "PowerShell"
      login-user:
        required: true
        type: string
        default: "CUSTADDS.com\\G9PERFTSTSVC"
      env_name:
        required: true
        type: string
        default: "mars"
      is-automation:
        required: true
        type: boolean
        default: true
      is-scheduled:
        required: true
        type: boolean
        default: false
      branch:
        required: true
        type: string
        default: "main"
      company-name:
        required: true
        type: string
        default: "Eckssohr21"

jobs:
  deploy-scripts:
    runs-on: ${{ inputs.runner-label }}
    steps:
      - name: Checkout correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Deploy JMeter Scripts
        uses: ./.github/actions/deploy-jmeter
        with:
          jmeter-test-node: ${{ inputs.jmeter-test-node }}
          jmeter-test-path: ${{ inputs.jmeter-test-path }}
          powershell-path: ${{ inputs.powershell-path }}
          login-user: ${{ inputs.login-user }}
          login-password: ${{ secrets.LOGIN_PASSWORD }}

  run-integrationstudio-test:
    runs-on: ${{ inputs.runner-label }}
    needs: deploy-scripts
    steps:
      - name: Checkout correct branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Run JMeter Test
        uses: ./.github/actions/integration-studio-ecksso-load
        with:
          env_name: ${{ inputs.env_name }}
          is-automation: ${{ inputs.is-automation }}
          is-scheduled: ${{ inputs.is-scheduled }}
          company-name: ${{ inputs.company-name }}
          runner-label: ${{ inputs.runner-label }}
