name: Run JMeter IntegrationStudio Test

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      is-automation:
        required: true
        type: boolean
      is-scheduled:
        required: true
        type: boolean
      pwsh:
        required: true
        type: string
      company-name:
        required: true
        type: string

jobs:
  run-jmeter-test:
    runs-on: [self-hosted, windows]

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      - name: Run IntegrationStudio_ECKSSO_LOAD
        shell: pwsh
        run: |
          $pwshPath = "${{ inputs.pwsh }}"
          $jmeterFile = "HR\\Main\\BJE\\IntegrationStudio_ECKSSO_LOAD.jmx"
          $envName = "${{ inputs.env_name }}"
          $gitRoot = "${{ github.workspace }}"
          $isAutomation = "${{ inputs.is-automation }}"
          $isScheduled = "${{ inputs.is-scheduled }}"
          $jmeterProperties = "-JINP_CompanyName=${{ inputs.company-name }}"

          .\PowerShell\Jmeter\JmeterRunTestInfluxdb.ps1 `
            -JmeterFile $jmeterFile `
            -Envname $envName `
            -GitRootFolder $gitRoot `
            -IsAutomation $isAutomation `
            -AdditionalInputVariables $jmeterProperties `
            -IsScheduled $isScheduled `
            -save $true `
            -run $true
