name: Trigger Metrics Collector

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      load_test_name:
        required: true
        type: string

jobs:
  trigger-metrics-collector:
    runs-on: [self-hosted, performance-engineering]

    steps:
      - name: Trigger metrics-collector workflow
        uses: DayforceGlobal/perfeng-tools/.github/workflows/metrics-collector.yml@main
        with:
          env_name: ${{ inputs.env_name }}
          load_test_name: ${{ inputs.load_test_name }}
